### ISSUE TITLE
Feature request: optional dependencies.

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#319]
I use cask to prepare environment for tests on travis.  When I test smartparens I run it on 5 emacs versions and some of my tests are for specific language modes, such as `latex-mode`, `ruby-mode` or `racket-mode`.

Unfortunatelly, `racket-mode` requires emacs 24.3 or higher, which means tests for 24.1 and 24.2 fail on `cask install` step with 

```
Dependency racket-mode failed to install: Package `emacs-24.3' is unavailable
```

This could be solved by having two cask files swapping for each test, but yuck?

A simple solution is to ignore unmet dependencies and continue... probably not very safe.  So what I would like is optional dependencies.  For start simply marking it as optional would mean that if it can't install no problem.  I already guard the tests in elisp so it would run fine.

Am I being clear? I feel like I'm describing it in a convoluted way :P Here's the failed job at travis https://travis-ci.org/Fuco1/smartparens/jobs/84581399

**Comment by rejeep** [comment]
Perhaps adding an `only` (and `except`) macro:

```lisp
(depends-on "foo" :only "24.3")
(depends-on "foo" :only ">= 24.3")
(depends-on "foo" :only ("24.2" "24.3"))

(only "24.3"
 (depends-on "foo"))

(only ">= 24.3"
 (depends-on "foo"))

(only ("24.2" "24.3")
 (depends-on "foo"))
```

**Comment by lunaryorn** [comment]
Alternatively, we could extend groups to allow user-specific groups (similar to bundler), i.e.

```
(depends on "foo")

(modern-emacs
   (depends-on "bar"))
```

And then `cask install --groups modern-emacs`.

**Comment by Fuco1** [comment]
@rejeep That would be a start, but then a package can also fail to install for other reasons than just version (i.e. some other package is missing or can't install due to version) which seems to me would then lead to me manually doing dep. resolution.

@lunaryorn That sounds interesting.  Do you have any idea how I could than use that in `.travis.yml`?  Here's my build script for travis: https://github.com/Fuco1/smartparens/blob/master/.travis.yml I only call `cask` at the end.  So I suppose I would add an `if` on `EVM_EMACS` right?

Would the groups allow inheritance?  For example the `develop-modern` would inherit from `develop`

**Comment by lunaryorn** [comment]
@Fuco1 I don't think that inheritance would be a great idea, when you can just give multiple groups to `install`, i.e. `cask install --groups develop,develop-modern`.

That way you wouldn't need `if` in `.travis.yml` either.  You can set multiple variables per matrix entry, i.e

```yaml
env:
  matrix:
    - EVM_EMACS=emacs-24.1-bin CASK_GROUPS=devel
    - EVM_EMACS=emacs-24.2-bin CASK_GROUPS=devel
    - EVM_EMACS=emacs-24.3-bin CASK_GROUPS=devel,devel-modern
    - EVM_EMACS=emacs-24.4-bin CASK_GROUPS=devel,devel-modern
    - EVM_EMACS=emacs-24.5-bin CASK_GROUPS=devel,devel-modern
install:
  …
  - cask install --groups="${CASK_GROUPS}:
```
