### ISSUE TITLE
Cask in travis with emacs <= 24.3

### ISSUE THREAD

**Issue by Ailrun** [cask/cask#380]
I try to use cask in travis, with ert-runner/evm, for testing purpose.

However, when I try to use it with emacs <= 24.3, I got a following error.

``` bash
$ cask --debug
Args out of range: 0
```

and without `--debug`, I got

``` bash
$ cask
Wrong type argument: stringp, listp
```

Travis setting file I used is,

``` yaml
# Use light weight image
language: C

sudo: false

notifications:
  email: false

env:
  matrix:
    - EVM_EMACS=emacs-24.1-travis
    - EVM_EMACS=emacs-24.2-travis
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis

before_install:
  - source ./travis.sh
  - evm install $EVM_EMACS --use --skip > /dev/null 2>&1
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask upgrade-cask
  - cask --debug

script:
  - emacs --version
  - cask exec ert-runner
```

and `./travis.sh` is

``` bash
#!/usr/bin/env bash

curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash

export PATH="$HOME/.evm/bin:$PATH"
export PATH="$HOME/.cask/bin:$PATH"

evm config path /tmp
```

Finally, my small Cask file is looks like

``` elisp
(source gnu)
(source melpa)

(package-file "<My-el-file-name>")

(files "*.el")

(depends-on "dash")

(development
  (depends-on "ert-runner"))
```

this.

Could anyone solve this issues? Is this my own mistake? If so, could you tell me the place that has something wrong?
